# Generated by Django 3.1.3 on 2021-12-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listtodo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoapp',
            name='id',
        ),
        migrations.AddField(
            model_name='todoapp',
            name='sno',
            field=models.AutoField(default=99, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
