# Generated by Django 3.1.3 on 2021-12-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listtodo', '0002_auto_20211226_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoapp',
            old_name='sno',
            new_name='id',
        ),
    ]
