# Generated by Django 3.2.10 on 2021-12-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listtodo', '0004_todoapp_file_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoapp',
            name='file_pic',
        ),
    ]
