# Generated by Django 3.2.10 on 2021-12-29 08:25

from django.db import migrations, models
import listtodo.models


class Migration(migrations.Migration):

    dependencies = [
        ('listtodo', '0006_todoapp_file_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todoapps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=60)),
                ('active', models.CharField(max_length=5)),
                ('file_pic', models.ImageField(upload_to=listtodo.models.user_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='todoapp',
            name='file_pic',
        ),
    ]
