# Generated by Django 3.1.3 on 2021-12-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listtodo', '0008_alter_todoapps_file_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('opposition', models.CharField(max_length=60)),
                ('venue', models.CharField(max_length=5)),
                ('file_pic', models.ImageField(upload_to='listtodo/static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Cricketapp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('opposition', models.CharField(max_length=60)),
                ('venue', models.CharField(max_length=5)),
            ],
        ),
    ]
